version: '3.9'
services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:${POSTGRES_VERSION}
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
